import gleam/list

pub type Concept {
  Concept(
    id: Int,
    domain: String,
    key: String,
    name_ja: String,
    name_en: String,
    description: String,
    layer: Int,
    source: String,
  )
}

pub fn all_concepts() -> List(Concept) {
  [
    Concept(1, "software", "agile", "アジャイル", "Agile", "要求の変化に応じて反復的に開発する手法", 3, "Agile Manifesto 2001"),
    Concept(2, "software", "waterfall", "ウォーターフォール", "Waterfall", "要件→設計→実装→検証の直線的プロセス", 3, "Royce 1970"),
    Concept(3, "software", "scrum", "スクラム", "Scrum", "小さなチームによるイテレーティブな開発フレームワーク", 3, "Sutherland & Schwaber"),
    Concept(4, "software", "iteration", "イテレーション", "Iteration", "短いサイクルでの開発と改善の反復", 3, ""),
    Concept(5, "software", "continuous_deployment", "継続的デプロイ", "Continuous Deployment", "コード変更を自動で本番環境へ反映する実践", 3, ""),
    Concept(6, "software", "refactoring", "リファクタリング", "Refactoring", "外部挙動を変えずに内部構造を改善する作業", 3, "Fowler 1999"),
    Concept(7, "software", "pull_request", "プルリクエスト", "Pull Request", "コード変更のレビューと統合を依頼する仕組み", 3, "GitHub"),
    Concept(8, "software", "code_review", "コードレビュー", "Code Review", "他者がコードを検査して品質を担保するプロセス", 3, ""),
    Concept(9, "software", "open_source", "オープンソース", "Open Source", "ソースコードを公開し誰でも改良できるライセンス形態", 4, "OSI"),
    Concept(10, "software", "cathedral_and_bazaar", "伽藍とバザール", "The Cathedral and the Bazaar", "秘匿的開発と公開的開発の対比", 4, "Raymond 1997"),
    Concept(11, "software", "design_pattern", "デザインパターン", "Design Pattern", "再利用可能なソフトウェア設計の解決策", 3, "GoF 1994"),
    Concept(12, "software", "software_crisis", "ソフトウェア危機", "Software Crisis", "1960年代のソフトウェア生産性・品質の問題", 5, "NATO 1968"),
    Concept(13, "software", "brooks_law", "ブルックスの法則", "Brooks's Law", "遅れたプロジェクトに人を追加するとさらに遅れる", 5, "Brooks 1975"),
    Concept(14, "software", "technical_debt", "技術的負債", "Technical Debt", "短期的な代償として後回しにした設計コスト", 3, "Cunningham"),
    Concept(15, "software", "dogfooding", "ドッグフーディング", "Dogfooding", "自社製品を自ら使用して品質確認する", 3, ""),
    Concept(16, "software", "yak_shaving", "ヤク剃り", "Yak Shaving", "本来の目的からどんどん脱線する作業の連鎖", 3, ""),
    Concept(17, "software", "rubber_duck_debugging", "ラバーダックデバッグ", "Rubber Duck Debugging", "無生物に説明することでバグを発見する技法", 3, ""),
    Concept(18, "software", "git", "Git", "Git", "分散型バージョン管理システム", 3, "Torvalds 2005"),
    Concept(19, "software", "version_control", "バージョン管理", "Version Control", "ファイルの変更履歴を管理するシステム", 3, ""),
    Concept(20, "software", "merge_conflict", "マージコンフリクト", "Merge Conflict", "複数の変更が衝突して自動統合できない状態", 3, ""),
    Concept(21, "software", "dependency_hell", "依存地獄", "Dependency Hell", "ライブラリ間の依存関係が複雑化して管理困難になる状態", 3, ""),
    Concept(22, "software", "api", "API", "API", "アプリケーション間のインターフェース", 3, ""),
    Concept(23, "software", "microservices", "マイクロサービス", "Microservices", "小さな独立したサービスの集合によるアーキテクチャ", 3, ""),
    Concept(24, "software", "monolith", "モノリス", "Monolith", "単一の大きなコードベースによるアーキテクチャ", 3, ""),
    Concept(25, "software", "container", "コンテナ", "Container", "アプリと実行環境をパッケージングする技術", 3, "Docker"),
    Concept(26, "software", "orchestration", "オーケストレーション", "Orchestration", "複数コンテナの運用を自動化・管理する", 3, "Kubernetes"),
    Concept(27, "software", "devops", "DevOps", "DevOps", "開発と運用の統合文化および実践", 3, ""),
    Concept(28, "software", "tdd", "テスト駆動開発", "Test-Driven Development", "テストを先に書く開発手法", 3, "Beck"),
    Concept(29, "software", "regression_test", "回帰テスト", "Regression Test", "変更後に既存機能が破壊されていないか確認するテスト", 3, ""),
    Concept(30, "software", "lint", "Lint", "Lint", "コードの静的解析による品質チェック", 3, ""),
    Concept(31, "software", "build", "ビルド", "Build", "ソースコードから実行可能な成果物を生成する過程", 3, ""),
    Concept(32, "software", "package_manager", "パッケージマネージャ", "Package Manager", "ライブラリの導入・更新・依存解決を行うツール", 3, ""),
    Concept(33, "software", "legacy_code", "レガシーコード", "Legacy Code", "古くて保守が困難な既存コード", 3, ""),
    Concept(34, "software", "abstraction", "抽象化", "Abstraction", "複雑性を隠蔽して本質に迫る操作", 2, ""),
    Concept(35, "software", "interface", "インターフェース", "Interface", "異なるシステム間の接続規約", 2, ""),
    Concept(36, "software", "state_machine", "状態機械", "State Machine", "状態と遷移で振る舞いをモデル化する", 2, ""),
    Concept(37, "architecture", "pattern_language", "パタン・ランゲージ", "Pattern Language", "建築における再現性ある解決策の言語化", 4, "Alexander 1977"),
    Concept(38, "architecture", "form_follows_function", "形式は機能に従う", "Form Follows Function", "設計の形態は目的に応じて決まる", 4, "Sullivan"),
    Concept(39, "architecture", "less_is_more", "少ないほど豊か", "Less is More", "簡潔さが本質を際立たせる", 4, "Mies van der Rohe"),
    Concept(40, "architecture", "brutalism", "ブルータリズム", "Brutalism", "素朴なコンクリート表現を特徴とする建築様式", 4, ""),
    Concept(41, "architecture", "deconstructivism", "デコンストラクティビズム", "Deconstructivism", "非線形・断片的なフォルムの建築動向", 4, ""),
    Concept(42, "architecture", "metabolism", "メタボリズム", "Metabolism", "成長と変化を前提とした日本の建築運動", 4, "Kurokawa, Kikutake"),
    Concept(43, "architecture", "critical_regionalism", "批判的地域主義", "Critical Regionalism", "グローバル普遍性と地域的文脈の融合", 4, "Frampton"),
    Concept(44, "architecture", "organic_architecture", "オーガニック建築", "Organic Architecture", "自然と一体化する建築思想", 4, "Wright"),
    Concept(45, "architecture", "vernacular_architecture", "在来建築", "Vernacular Architecture", "地域の素材と技術に根ざした建築", 4, ""),
    Concept(46, "architecture", "spatial_sequence", "空間連続", "Spatial Sequence", "連続する空間体験の設計", 3, ""),
    Concept(47, "architecture", "circulation", "動線", "Circulation", "建物内の移動経路の計画", 3, ""),
    Concept(48, "architecture", "program", "プログラム", "Program", "建築における用途・機能・行為の計画", 3, ""),
    Concept(49, "architecture", "plan", "平面図", "Plan", "水平断面による建築の配置表現", 3, ""),
    Concept(50, "architecture", "section", "断面図", "Section", "垂直断面による空間関係の表現", 3, ""),
    Concept(51, "architecture", "elevation", "立面図", "Elevation", "建物外壁の正投影図", 3, ""),
    Concept(52, "architecture", "massing", "立体構成", "Massing", "建築物の三次元的な塊の構成", 3, ""),
    Concept(53, "architecture", "materiality", "マテリアリティ", "Materiality", "素材の質感・表現における重視", 3, ""),
    Concept(54, "architecture", "tectonics", "テクトニクス", "Tectonics", "構造と構成の芸術的表現", 3, ""),
    Concept(55, "architecture", "joint", "接合", "Joint", "部材同士の接続部位の設計", 3, ""),
    Concept(56, "architecture", "proportion", "プロポーション", "Proportion", "部分と全体の数的関係", 3, ""),
    Concept(57, "architecture", "scale", "スケール", "Scale", "物体と人間の相対的な大きさ関係", 3, ""),
    Concept(58, "architecture", "context", "文脈", "Context", "建築を取り巻く環境・文化・社会的条件", 3, ""),
    Concept(59, "architecture", "genius_loci", "ゲニウス・ロキ", "Genius Loci", "場の固有の精神や表象", 3, "Norberg-Schulz"),
    Concept(60, "architecture", "adaptive_reuse", "適応的再利用", "Adaptive Reuse", "既存建築を新たな用途へ適応させる", 3, ""),
    Concept(61, "architecture", "renovation", "改修", "Renovation", "既存建築の修復・更新", 3, ""),
    Concept(62, "architecture", "self_build", "自力建築", "Self-Build", "設計者自身が施工する建築生産形態", 3, ""),
    Concept(63, "architecture", "hand_mixed_concrete", "手練りコンクリート", "Hand-Mixed Concrete", "現場で手作業で練るコンクリート技術", 3, ""),
    Concept(64, "architecture", "incremental_housing", "漸進的住宅", "Incremental Housing", "住戸の段階的な拡張・改築を前提とする住宅", 3, ""),
    Concept(65, "architecture", "participatory_design", "参加型設計", "Participatory Design", "ユーザーや地域住民が設計プロセスに参加", 3, ""),
    Concept(66, "architecture", "informal_settlement", "非公式定住地", "Informal Settlement", "法的・制度的規制外に形成される集住形態", 3, ""),
    Concept(67, "architecture", "feng_shui", "風水", "Feng Shui", "環境と気の流れを調整する中国伝統的空間思想", 5, ""),
    Concept(68, "architecture", "vastu_shastra", "ヴァーストゥ・シャーストラ", "Vastu Shastra", "古代インドの建築・空間の法則書", 5, ""),
    Concept(69, "architecture", "nakagin_capsule_tower", "中銀カプセルタワー", "Nakagin Capsule Tower", "黒川紀章によるカプセル型集合住宅", 4, ""),
    Concept(70, "architecture", "ants_masutorinburu", "蟻鱒鳶ル", "Ants Masutorinburu", "岡啓輔による東京・三田の自力建築", 3, ""),
    Concept(71, "architecture", "autonomous_architecture", "自律的建築", "Autonomous Architecture", "外部システムに依存しない自己完足的建築", 3, ""),
    Concept(72, "architecture", "construction_management", "施工管理", "Construction Management", "建設工程の計画・監督・調整", 3, ""),
    Concept(73, "philosophy", "deconstruction", "脱構築", "Deconstruction", "テクストの固定された意味を解体する戦略", 4, "Derrida"),
    Concept(74, "philosophy", "differance", "ディフェランス", "Différance", "意味の無限に後退する差異化作用", 4, "Derrida"),
    Concept(75, "philosophy", "logocentrism", "ロゴセントリズム", "Logocentrism", "音声と理性を中心に置く西洋形而上学の傾向", 4, "Derrida"),
    Concept(76, "philosophy", "trace", "痕跡", "Trace", "存在の根底にある不在の印", 4, "Derrida"),
    Concept(77, "philosophy", "supplement", "補充", "Supplement", "不足を埋めるものでありながら元を相対化するもの", 4, "Derrida"),
    Concept(78, "philosophy", "arche_writing", "原書", "Arche-writing", "音声を含むすべての記号活動の根源的基底", 4, "Derrida"),
    Concept(79, "philosophy", "postal", "郵便的", "The Postal", "メッセージの誤配と宛先の不確定性", 4, "Derrida / Azuma"),
    Concept(80, "philosophy", "animalization", "動物化", "Animalization", "ポストモダンにおける消費主体の変容", 4, "Azuma"),
    Concept(81, "philosophy", "database_consumption", "データベース消費", "Database Consumption", "大きな物語に代わるデータベースとしての作品消費", 4, "Azuma"),
    Concept(82, "philosophy", "grand_narrative", "大きな物語", "Grand Narrative", "社会全体を説明する統一的物語", 4, "Lyotard"),
    Concept(83, "philosophy", "general_will_2", "一般意志2.0", "General Will 2.0", "SNS時代の集合的意志のデータベース化", 4, "Azuma"),
    Concept(84, "philosophy", "hermeneutics", "解釈学", "Hermeneutics", "テクスト理解の方法と理論", 4, "Gadamer"),
    Concept(85, "philosophy", "phenomenology", "現象学", "Phenomenology", "意識の中での現象のあり方を記述する哲学", 4, "Husserl"),
    Concept(86, "philosophy", "dasein", "此在", "Dasein", "自己の存在を問う存在者", 4, "Heidegger"),
    Concept(87, "philosophy", "being_in_the_world", "世界内存在", "Being-in-the-World", "人間が世界と不可分に結びついている存在構造", 4, "Heidegger"),
    Concept(88, "philosophy", "poiesis", "ポイエーシス", "Poiesis", "自然に似せて何かを生み出す活動全体", 4, "Aristotle / Heidegger"),
    Concept(89, "philosophy", "techne", "テクネー", "Techne", "知識に裏打ちされた制作技術", 4, "Aristotle"),
    Concept(90, "philosophy", "episteme", "エピステーメー", "Episteme", "普遍的・証明的な知識", 4, "Aristotle / Foucault"),
    Concept(91, "philosophy", "phronesis", "フロネーシス", "Phronesis", "実践的知恵・熟慮", 4, "Aristotle"),
    Concept(92, "philosophy", "monadology", "単子論", "Monadology", "個の実体としての単子が調和する宇宙観", 4, "Leibniz"),
    Concept(93, "philosophy", "rhizome", "リゾーム", "Rhizome", "中心・階層を持たないネットワーク的モデル", 4, "Deleuze & Guattari"),
    Concept(94, "philosophy", "deterritorialization", "脱領域化", "Deterritorialization", "既存の領域・コードからの解放運動", 4, "Deleuze & Guattari"),
    Concept(95, "philosophy", "body_without_organs", "脳肢体なき身体", "Body without Organs", "欲望の機械としての抽象的身体", 4, "Deleuze & Guattari"),
    Concept(96, "philosophy", "assemblage", "アッサンブラージュ", "Assemblage", "異質な要素の機能的結合", 4, "Deleuze"),
    Concept(97, "philosophy", "simulacrum", "シミュラークル", "Simulacrum", "原型を持たない模像・擬像", 4, "Baudrillard"),
    Concept(98, "philosophy", "hyperreality", "ハイパーリアリティ", "Hyperreality", "現実と区別つかない模倣の領域", 4, "Baudrillard"),
    Concept(99, "philosophy", "panopticon", "パノプティコン", "Panopticon", "常に見られている可能性による自己統制装置", 4, "Foucault / Bentham"),
    Concept(100, "philosophy", "power_knowledge", "権力と知識", "Power/Knowledge", "権力と知識の相互生産関係", 4, "Foucault"),
    Concept(101, "philosophy", "biopolitics", "バイオポリティクス", "Biopolitics", "人口・生命に作用する近代権力", 4, "Foucault"),
    Concept(102, "philosophy", "heterotopia", "異托邦", "Heterotopia", "社会的空間の中の異質な位置", 4, "Foucault"),
    Concept(103, "philosophy", "discourse", "ディスクール", "Discourse", "言語実践と知の体制を含む言説形成", 4, "Foucault"),
    Concept(104, "philosophy", "structuralism", "構造主義", "Structuralism", "文化的現象の背後にある構造を重視", 4, "Levi-Strauss, Saussure"),
    Concept(105, "philosophy", "post_structuralism", "ポスト構造主義", "Post-Structuralism", "構造の固定性と中心性を批判する思想", 4, ""),
    Concept(106, "philosophy", "genealogical_method", "系譜学的方法", "Genealogical Method", "起源ではなく歴史的経緯と権力を追跡する方法", 4, "Foucault / Nietzsche"),
    Concept(107, "philosophy", "death_of_the_author", "作者の死", "Death of the Author", "作者の意図からテクストを解放する", 4, "Barthes"),
    Concept(108, "philosophy", "intertextuality", "インターテクスト性", "Intertextuality", "テクスト間の相互参照と網目構造", 4, "Kristeva"),
    Concept(109, "ecology", "ecosystem", "生態系", "Ecosystem", "生物群集と環境が相互作用する動的システム", 3, "Tansley 1935"),
    Concept(110, "ecology", "food_chain", "食物連鎖", "Food Chain", "生物間のエネルギー伝達の連鎖的関係", 3, ""),
    Concept(111, "ecology", "biota", "生物相", "Biota", "特定の地域・時期に生息する生物の総体", 3, ""),
    Concept(112, "ecology", "habitat", "生息地", "Habitat", "種が生存・繁殖するための物理的環境", 3, ""),
    Concept(113, "ecology", "niche", "ニッチ", "Niche", "種が占める環境条件と機能的地位の総体", 3, "Grinnell / Elton"),
    Concept(114, "ecology", "niche_partitioning", "生態位的分離", "Niche Partitioning", "複数種が資源を分け合って共存する機構", 3, ""),
    Concept(115, "ecology", "mutualism", "相利共生", "Mutualism", "互いに利益を得る種間関係", 3, ""),
    Concept(116, "ecology", "commensalism", "偏利共生", "Commensalism", "一方が利益を得て他方に影響を与えない関係", 3, ""),
    Concept(117, "ecology", "parasitism", "寄生", "Parasitism", "一方が宿主から栄養を得て宿主に害を与える関係", 3, ""),
    Concept(118, "ecology", "competitive_exclusion", "競争排除の原理", "Competitive Exclusion Principle", "同一ニッチの種は共存できず一方が排除される", 3, "Gause"),
    Concept(119, "ecology", "carrying_capacity", "キャリング・キャパシティ", "Carrying Capacity", "環境が維持可能な個体群の最大サイズ", 3, ""),
    Concept(120, "ecology", "succession", "遷移", "Succession", "群落が環境変化に応じて段階的に遷る動的プロセス", 3, ""),
    Concept(121, "ecology", "climax_community", "頂極群落", "Climax Community", "遷移の最終段階で安定した群落", 3, "Clements"),
    Concept(122, "ecology", "nutrient_cycle", "物質循環", "Nutrient Cycle", "生態系内での栄養素の循環と再利用", 3, ""),
    Concept(123, "ecology", "energy_flow", "エネルギー・フロー", "Energy Flow", "生態系内で一方向に流れ減衰するエネルギー", 3, "Lindeman"),
    Concept(124, "ecology", "ecosystem_services", "生態系サービス", "Ecosystem Services", "生態系が人間社会に提供する恩恵の総称", 3, "MEA 2005"),
    Concept(125, "ecology", "biodiversity", "生物多様性", "Biodiversity", "生命のあらゆるレベルの多様性", 3, "Wilson"),
    Concept(126, "ecology", "genetic_diversity", "遺伝的多様性", "Genetic Diversity", "同一種内の遺伝子の多様性", 3, ""),
    Concept(127, "ecology", "species_diversity", "種多様性", "Species Diversity", "地域に生息する種の豊富さと均等度", 3, ""),
    Concept(128, "ecology", "ecosystem_diversity", "生態系多様性", "Ecosystem Diversity", "生態系タイプの多様性", 3, ""),
    Concept(129, "ecology", "invasive_species", "侵略的外来種", "Invasive Species", "新たな生態系で生態的・経済的被害を与える外来種", 3, ""),
    Concept(130, "ecology", "native_species", "在来種", "Native Species", "その地域の進化史に根ざした固有の種", 3, ""),
    Concept(131, "ecology", "conservation_ecology", "保全生態学", "Conservation Ecology", "絶滅リスクの低減と生息地保全を目指す学問", 3, ""),
    Concept(132, "ecology", "restoration_ecology", "回復生態学", "Restoration Ecology", "破壊された生態系の回復・再生を研究する学問", 3, ""),
    Concept(133, "ecology", "keystone_species", "キーストン種", "Keystone Species", "他種への影響が質的に大きい種", 3, "Paine"),
    Concept(134, "ecology", "indicator_species", "指標種", "Indicator Species", "環境状態を示すために利用される種", 3, ""),
    Concept(135, "ecology", "foundation_species", "基礎種", "Foundation Species", "群落の構造を形成し生息地を提供する種", 3, ""),
    Concept(136, "ecology", "trophic_cascade", "トロフィック・カスケード", "Trophic Cascade", "食物連鎖を伝わる間接的な上から下への影響", 3, ""),
    Concept(137, "ecology", "bottom_up_top_down", "ボトムアップ対トップダウン", "Bottom-Up vs Top-Down", "資源制約と捕食者制御の相対的優位性", 3, ""),
    Concept(138, "ecology", "community", "群集", "Community", "同一生態系内で相互作用する複数種の集合", 3, ""),
    Concept(139, "ecology", "population", "個体群", "Population", "同一種の個体が同一地域に集まる群れ", 3, ""),
    Concept(140, "ecology", "metapopulation", "メタ個体群", "Metapopulation", "複数の局所個体群が移入・絶滅を繰り返す集合", 3, "Levins"),
    Concept(141, "ecology", "r_k_selection", "r/K選択説", "r/K Selection Theory", "不安定環境での多産と安定環境での少数育成の戦略", 3, "MacArthur & Wilson"),
    Concept(142, "ecology", "swarm_intelligence", "群れ知能", "Swarm Intelligence", "単純な個体の相互作用から生じる集合的智能", 3, ""),
    Concept(143, "ecology", "emergence", "創発（湧現）", "Emergence", "部分の相互作用から全体としての新性質が生じる現象", 2, ""),
    Concept(144, "ecology", "self_organization", "自己組織化", "Self-Organization", "外部からの指示なしに秩序が生成されるプロセス", 2, ""),
    Concept(145, "ecology", "homeostasis", "ホメオスタシス", "Homeostasis", "生態系が内部環境を一定に保つ動的平衡機構", 3, ""),
    Concept(146, "ecology", "feedback_loop", "フィードバック・ループ", "Feedback Loop", "出力が入力に影響を与える因果循環回路", 3, ""),
    Concept(147, "ecology", "resilience", "レジリエンス", "Resilience", "撹乱後に元の状態へ回復する能力", 3, "Holling"),
    Concept(148, "ecology", "vulnerability", "脆弱性", "Vulnerability", "撹乱に対する感受性と適応能力の欠如", 3, ""),
  ]
}

pub fn count() -> Int {
  148
}
